export const LOAD_SITES_SUCCESS = 'LOAD_SITES_SUCCESS';
export const CREATE_SITE_SUCCESS = 'CREATE_SITE_SUCCESS';
export const UPDATE_SITE_SUCCESS = 'UPDATE_SITE_SUCCESS';
// export const UPVOTE_SITE_SUCCESS = "UPVOTE_SITE_SUCCESS";


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
